# Generated by Django 4.2.4 on 2023-08-05 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_name', models.CharField(max_length=100)),
                ('num_members', models.PositiveIntegerField()),
                ('seat_number', models.PositiveIntegerField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.cabin')),
            ],
        ),
    ]
