# Generated by Django 4.2.4 on 2023-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='fare',
            field=models.PositiveIntegerField(),
        ),
    ]
